name: lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: Linux-centos-10-198-4-167
    steps:
      - name: pre-commit hook
        run: |
          pwd&&ls
          sleep 15
          pwd&&ls
          new_dir=`ls -lt .|awk '{print $9}'|sed -n 2p`
          echo $new_dir
          cd $new_dir
          git fetch
          updated_files=`git diff --name-status remotes/origin/master HEAD|awk '{print$ 2}'`
          for file in $updated_files
          do
            if [ "${file##*.}" = "py" ]; then
              echo $file
              pre-commit run --files $file --show-diff-on-failure
            fi
          done
