name: lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: Linux-centos-10-198-4-167
    steps:
      - name: pre-commit hook
        run: |
          pwd&&ls
          config_yaml_file=$(sudo find . -name .pre-commit-config.yaml)
          ppq_dir=${config_yaml_file%/*}
          echo $ppq_dir
          cd $ppq_dir
          pre-commit run --files ProgramEntrance_1.py
