name: lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install pre-commit hook
        run: |
          # markdownlint requires ruby >= 2.7
          # sudo apt-add-repository ppa:brightbox/ruby-ng -y
          # sudo apt-get update
          # sudo apt-get install -y ruby2.7
          # pip install pre-commit
          # pre-commit install
          pwd&&ls
          pip install pre-commit
          pre-commit --version
          git fetch
          git branch -a
      - name: pre-commit checking
        run: |
          updated_files=`git diff --name-status remotes/origin/master HEAD|awk '{print$ 2}'`          for file in $updated_files
          do
            if [ "${file##*.}" = "py" ]; then
              echo $file
              pre-commit run --files $file --show-diff-on-failure
            fi
          done
